services:
  # Main Go API
  - type: web
    name: hyfnd-go-api
    env: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8080
      # URL to your Hugging Face Space ML Service
      - key: ML_SERVICE_URL
        value: https://Naman30903-fake-news-detector.hf.space
